print("Please enter your roll number (The last two digits only)")
rollno = int(input())
print("Please enter your Name ")
name = input()
print("Please enter your Address in sigle line ")
address = input()
print("Please enter your Blood group")
bloodgrp = input()
print("Please enter your Phone Number (if any code begin with 00---)")
pnum = int(input())
print("Please enter your Department to which you have assigned")
department = input()
print("Student Info")
print("The Roll number of students is ")
print(rollno)
print("The Name of students is ")
print(name)
print("The Address of students is ")
print(address)
print("The Blood group of students is ")
print(bloodgrp)
print("The Phone number of students is ")
print(pnum)
print("The Department of students is ")
print(department)
